// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaD3RJ4IDX5GdtYYmxfdKB2Ry6OA0L_4Q',
    appId: '1:125257675483:web:0400a8e64a6965592052fe',
    messagingSenderId: '125257675483',
    projectId: 'marvel-guide-34795',
    authDomain: 'marvel-guide-34795.firebaseapp.com',
    storageBucket: 'marvel-guide-34795.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-cq9ndv2HamImZTb8HRVL5m4F5T4s40',
    appId: '1:125257675483:android:66dc30ffed35f7022052fe',
    messagingSenderId: '125257675483',
    projectId: 'marvel-guide-34795',
    storageBucket: 'marvel-guide-34795.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHuYDNmubGNoYMJWZCl6g3Hc2iyBSjaqc',
    appId: '1:125257675483:ios:c817d2c43734c2b12052fe',
    messagingSenderId: '125257675483',
    projectId: 'marvel-guide-34795',
    storageBucket: 'marvel-guide-34795.appspot.com',
    iosClientId:
        '125257675483-9bkn5sjkfm1kv1a140574fr4qp4nn6kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.marvelGuide',
  );
}
